#!/usr/bin/env python3
"""Embed the Aseprite-generated PNGs into src/assets.h for the libretro core.

Run from brick/:  python3 tools/png2c.py
Reads ../assets/{tiles,font,logo}.png and the font charset from ../assets/layout.js.
"""
import pathlib
import re

from PIL import Image

HERE = pathlib.Path(__file__).resolve().parent.parent
ASSETS = HERE.parent / "assets"
OUT = HERE / "src" / "assets.h"


def emit(name, path):
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    raw = img.tobytes()
    px = [(raw[i + 3] << 24) | (raw[i] << 16) | (raw[i + 1] << 8) | raw[i + 2]
          for i in range(0, len(raw), 4)]
    rows = ",\n".join(
        "  " + ",".join(f"0x{v:08x}" for v in px[i:i + 12]) for i in range(0, len(px), 12)
    )
    return (f"#define {name}_W {w}\n#define {name}_H {h}\n"
            f"static const uint32_t {name}[{w * h}] = {{\n{rows}\n}};\n")


def main():
    layout = (ASSETS / "layout.js").read_text()
    chars = re.search(r'fontChars:\s*"((?:[^"\\]|\\.)*)"', layout).group(1)
    chars = chars.replace("\\\\", "\\").replace('\\"', '"')
    esc = chars.replace("\\", "\\\\").replace('"', '\\"')
    parts = [
        "/* generated by tools/png2c.py from ../assets — do not edit by hand */",
        "#ifndef PIXELTETRIS_ASSETS_H", "#define PIXELTETRIS_ASSETS_H", "#include <stdint.h>",
        f'static const char FONT_CHARS[] = "{esc}";',
        emit("IMG_TILES", ASSETS / "tiles.png"),
        emit("IMG_FONT", ASSETS / "font.png"),
        emit("IMG_LOGO", ASSETS / "logo.png"),
        "#endif",
    ]
    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT.relative_to(HERE)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
